# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMinimumSize(QtCore.QSize(428, 303))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setIndent(-1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 4)
        self.checkZaloData = QtWidgets.QCheckBox(self.centralwidget)
        self.checkZaloData.setMinimumSize(QtCore.QSize(66, 0))
        self.checkZaloData.setObjectName("checkZaloData")
        self.gridLayout.addWidget(self.checkZaloData, 3, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 4, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 5, 0, 1, 4)
        self.moveButton = QtWidgets.QPushButton(self.centralwidget)
        self.moveButton.setObjectName("moveButton")
        self.gridLayout.addWidget(self.moveButton, 4, 2, 1, 2)
        self.newPath = QtWidgets.QLineEdit(self.centralwidget)
        self.newPath.setObjectName("newPath")
        self.gridLayout.addWidget(self.newPath, 1, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.checkZalo = QtWidgets.QCheckBox(self.centralwidget)
        self.checkZalo.setMinimumSize(QtCore.QSize(97, 0))
        self.checkZalo.setObjectName("checkZalo")
        self.gridLayout.addWidget(self.checkZalo, 3, 0, 1, 1)
        self.checkZaloPC = QtWidgets.QCheckBox(self.centralwidget)
        self.checkZaloPC.setMinimumSize(QtCore.QSize(174, 0))
        self.checkZaloPC.setObjectName("checkZaloPC")
        self.gridLayout.addWidget(self.checkZaloPC, 3, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 428, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "ZaloMove 1.0 - Developed by Shun"))
        self.checkZaloData.setText(_translate("MainWindow", "ZaloData"))
        self.label.setText(_translate("MainWindow", "New Folder Location"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.moveButton.setText(_translate("MainWindow", "Move Zalo Folder"))
        self.label_3.setText(_translate("MainWindow", "Select folder you want to move:"))
        self.checkZalo.setText(_translate("MainWindow", "Zalo"))
        self.checkZaloPC.setText(_translate("MainWindow", "ZaloPC"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
